<a href="https://colab.research.google.com/github/VishalNaik2/piTorch/blob/main/pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [2]:
|my_list=[1,2,3,45]
my_list

[1, 2, 3, 45]

In [5]:
np1=np.random.rand(3,3)
np1

array([[0.5370359 , 0.57437566, 0.39373073],
       [0.09206081, 0.15274603, 0.3509745 ],
       [0.64598035, 0.11027611, 0.14534104]])

In [6]:
np1.dtype

dtype('float64')

In [10]:
tns1=torch.randn(2,3)
tns1

tensor([[-0.5681, -0.5674,  0.2237],
        [ 0.4958, -0.5181, -1.2000]])

In [15]:
tns2=torch.zeros(2,3,4)
tns2
tns2.dtype

torch.float32

In [14]:
#create tesnor from np array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.5370, 0.5744, 0.3937],
        [0.0921, 0.1527, 0.3510],
        [0.6460, 0.1103, 0.1453]], dtype=torch.float64)

2nd video yt


In [20]:
my_torch=torch.arange(15)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# reshape and view
my_torch = my_torch.reshape(3,5)
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
# Reshape if we don't know the number of item usng -1
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_torch2=my_torch2.reshape(5,-1)
my_torch2

#same thing can be don throw view

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [41]:
#changing the array
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
my_torch3[2]=5656
my_torch3
my_torch4

tensor([[   0,    1, 5656,    3,    4],
        [   5,    6,    7,    8,    9]])

In [42]:
my_torch5=my_torch3.view(5,-1)
my_torch5[:,1]

tensor([1, 3, 5, 7, 9])

In [44]:
my_torch5[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [4]:
a=torch.tensor([1,2,3,5,6])
b=torch.tensor([5,4,3,10,12])
a+b



tensor([ 6,  6,  6, 15, 18])

In [9]:
a-b


tensor([-4, -2,  0, -5, -6])

In [6]:
a*b


tensor([ 5,  8,  9, 50, 72])

In [7]:
b/a


tensor([5., 2., 1., 2., 2.])

In [8]:
b%a


tensor([0, 0, 0, 0, 0])

In [10]:
torch.add(a,b)

tensor([ 6,  6,  6, 15, 18])

In [11]:
a.add_(b)

tensor([ 6,  6,  6, 15, 18])

In [12]:
a

tensor([ 6,  6,  6, 15, 18])